projects:
  conveyorsApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 2prmd3ksgvgybejrox2lxburwe
      endpoints:
        prod: >-
          https://tl4kge64mncefddb4atv7qecuq.appsync-api.us-east-1.amazonaws.com/graphql
