# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'conveyorsAmplify' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for conveyorsAmplify

  target 'conveyorsAmplify-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'conveyorsAmplifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'conveyorsAmplify-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for conveyorsAmplify-tvOS

end

pod 'Firebase/Core'
